# -*- coding: utf-8 -*-
"""upload_model_to_gcs

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1LZ9uAjHY9w-PFtzU90vqmOEzXKELC7h_
"""

from google.cloud import storage

# Set up GCS client
client = storage.Client()

# Create a GCS bucket (if it doesn't exist)
bucket_name = 'model_obeng'
bucket = client.create_bucket(bucket_name)

# Upload the TFLite model file to GCS
blob_name = 'model.tflite'
blob = bucket.blob(blob_name)
blob.upload_from_filename('model.tflite')

print(f"Model uploaded to GCS: gs://{bucket_name}/{blob_name}")